### ISSUE TITLE
vendor文件夹呢？

### ISSUE THREAD

**Issue by wangold** [yzslab/whmcs-wechatpay#1]
wechatpay.php 上有：
`require __DIR__ . "/WeChatPay/vendor/autoload.php";`
下载的文件包没看见呀！

**Comment by yzslab** [comment]
3. 到本项目的Release页面下载模块文件，把解包后的文件放入WHMCS根目录下的modules/gateways/目录中

Release页面下载的才有vendor：https://github.com/yzslab/whmcs-wechatpay/releases

**Comment by wangold** [comment]
我是到releases里下的zip包，还是没有哦，难道操作不对？
<img width="977" alt="Screen Shot 2021-01-27 at 3 12 18 AM" src="https://user-images.githubusercontent.com/22538553/105893111-a4e2b000-604d-11eb-9e94-05db007dcf3d.png">

**Comment by yzslab** [comment]
下载whmcs-wechatpay.tar.bz2

**Comment by yzslab** [comment]
你下载的是Source code吧

**Comment by wangold** [comment]
@yzslab 抱歉，熬夜昏头了，很棒的分享，谢谢，我先测试一下，如若有问题再请教您！
